config/routes.rb
Rails.application.routes.draw do

  resources :links
  resources :views, path: :v, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :views, dependent: :destroy
  scope :recent_first, -> {order(created_at: :desc)}

  validates :url, presence: true

  def self.find(id)
    super ShortCode.decode(id)
  end
  def to_param
    ShortCode.encode(id)
  end

end

app/models/short_code.rb
class ShortCode
  ALPHABET ="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length
  def self.encode(number)
    return ALPHABET.first if number.zero? || number.nil?
    result = ""

    while number > 0 do
      index = number % BASE
      char = ALPHABET[index]
      result.prepend char
      number = number / BASE
    end

    result
  end

  def self.decode(string)
    number = 0

    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET.index(char)
      number += index * power
    end

    number
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show]
  def index
    @links = Link.recent_first
  end

  def show
  end


  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to root_path
    else
      index
      render :index, status: :unprocessable_entity
    end
  end


  private

  def link_params
    params.require(:link).permit(:url)
  end

  def set_link
    @link = Link.find(params[:id])
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

  def show
    @link.views.create(ip: request.ip, user_agent: request.user_agent)
    redirect_to @link.url, allow_other_host: true
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="prose mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
  <%= link_to link.to_param, link %>
  <%= link.url %>
  <%= pluralize link.views_count, "view" %>

  <%= link_to view_path(link), target: :_blank, data: {turbo: false}  do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
    </svg>
  <% end %>

  <% end  %>

app/views/links/index.html.erb
<h1> Links Shortener </h1>

<%= form_with model: Link.new do |form| %>
  <div class="flex gap-2 items-center">
    <%= form.url_field :url, autofocus: true, require: true, placeholder: "https://example.org", class:"flex-grow rounded" %>
    <%= form.button "Save", class: "px-3 py-2 bg-gray-100 rounded" %>
  </div>
<% end %>

<%= render @links %>
